#!/usr/bin/env bash
set -euo pipefail

fail() { echo "test-beta-backup-migration.sh: $1" >&2; exit 1; }
root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
tmp=$(mktemp -d)
trap 'rm -r -- "$tmp"' EXIT HUP INT TERM

source_dir="$tmp/source"
destination_dir="$tmp/destination"
storage_root="$tmp/storage"
restore_output="$tmp/restore-output"
proof="$tmp/migration-proof.json"
mkdir -p "$source_dir" "$destination_dir" "$storage_root"
printf 'encrypted database fixture\n' >"$source_dir/postgres.dump.age"
printf 'encrypted uploads fixture\n' >"$source_dir/uploads.tar.gz.age"
source_revision=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
restore_revision=bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
capture_command=$(printf reviewed-capture | sha256sum | awk '{print $1}')
evidence_digest=$(printf reviewed-evidence | sha256sum | awk '{print $1}')
contract_digest=$(printf reviewed-contract | sha256sum | awk '{print $1}')
proof_digest=$(printf reviewed-proof | sha256sum | awk '{print $1}')
cat >"$source_dir/recovery-point.json" <<EOF
{"capture":{"capturedAt":1790000000,"sourceRevision":"$source_revision"},"captureCommandDigest":"$capture_command","captureEvidenceDigest":"$evidence_digest","contractDigest":"$contract_digest","pointId":"slot-1790000000","proofDigest":"$proof_digest","runtimeRevision":"$restore_revision","schema":"meet-backend/beta-recovery-point/v2","slotId":"1790000000"}
EOF
cp -- "$source_dir/recovery-point.json" "$tmp/original-manifest.json"
cat >"$tmp/restore-command.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
point='' proof='' output='' capture='' restore=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --point-dir) point=$2; shift 2 ;;
    --identity-file) identity=$2; shift 2 ;;
    --output-dir) output=$2; shift 2 ;;
    --proof-output) proof=$2; shift 2 ;;
    --capture-revision) capture=$2; shift 2 ;;
    --restore-revision) restore=$2; shift 2 ;;
    *) exit 2 ;;
  esac
done
[ -s "$identity" ] && [ -d "$output" ] && [ -z "$(find "$output" -mindepth 1 -print -quit)" ]
descriptor=$(sha256sum "$point/point.json" | awk '{print $1}')
captured=$(jq -er '.capture.capturedAt' "$point/recovery-point.json")
fingerprint=$(printf isolated | sha256sum | awk '{print $1}')
jq -cnS --arg capture "$capture" --arg restore "$restore" \
  --arg descriptor "$descriptor" --argjson captured "$captured" \
  --arg fingerprint "$fingerprint" \
  '{schema:"meet-backend/beta-backup-migration-proof/v1",
    captureRevision:$capture,restoreRevision:$restore,capturedAt:$captured,
    pointDescriptorDigest:$descriptor,identityCustody:"restore-only",
    isolated:true,databaseProbe:true,mediaProbe:true,cleanup:true,
    preFingerprint:$fingerprint,postFingerprint:("f"+$fingerprint[1:])}' >"$proof"
EOF
chmod 755 "$tmp/restore-command.sh"
printf 'migration identity\n' >"$tmp/identity"
manifest_before=$(sha256sum "$source_dir/recovery-point.json" | awk '{print $1}')
db_before=$(sha256sum "$source_dir/postgres.dump.age" | awk '{print $1}')
media_before=$(sha256sum "$source_dir/uploads.tar.gz.age" | awk '{print $1}')
"$root/scripts/migrate-beta-backup-artifact.sh" \
  --source "$source_dir" --destination "$destination_dir" \
  --manifest "$source_dir/recovery-point.json" --storage-root "$storage_root" \
  --restore-command "$tmp/restore-command.sh" --restore-output "$restore_output" \
  --identity-file "$tmp/identity" --capture-revision "$source_revision" \
  --restore-revision "$restore_revision" --proof-output "$proof" >/dev/null ||
  fail "destination restore migration was rejected"
cmp -- "$tmp/original-manifest.json" "$source_dir/recovery-point.json" ||
  fail "source manifest changed during migration"
[ "$manifest_before" = "$(sha256sum "$source_dir/recovery-point.json" | awk '{print $1}')" ] &&
  [ "$db_before" = "$(sha256sum "$source_dir/postgres.dump.age" | awk '{print $1}')" ] &&
  [ "$media_before" = "$(sha256sum "$source_dir/uploads.tar.gz.age" | awk '{print $1}')" ] ||
  fail "source ciphertext/provenance changed during migration"
jq -e '.schema=="meet-backend/beta-backup-migration-proof/v1" and
  .pointDescriptorDigest and .preFingerprint != .postFingerprint' "$proof" >/dev/null ||
  fail "migration proof was not generated by restore"
provider_count=$("$root/scripts/run-beta-backup-storage.sh" provider-list \
  --storage-root "$storage_root" | jq 'length')
[ "$provider_count" -eq 2 ] || fail "versioned provider inventory is incomplete"
printf 'test-beta-backup-migration.sh: passed\n'
